# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-11-21 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('short_description', models.CharField(default='short description', max_length=20)),
                ('full_description', models.CharField(default='full description', max_length=256)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(default='default', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='State',
            field=models.CharField(default='(state)', max_length=10),
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(default='(address', max_length=128),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='(city)', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='employees',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=17, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=17, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='street',
            field=models.CharField(default='(street)', max_length=128),
        ),
        migrations.AddField(
            model_name='location',
            name='website',
            field=models.CharField(default='(website)', max_length=128),
        ),
        migrations.AddField(
            model_name='location',
            name='zip',
            field=models.IntegerField(default=99999),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='(name)', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('User', 'Regular User'), ('Location Employee', 'Location Employee'), ('Manager', 'Manager'), ('Admin', 'Admin')], default='User', max_length=1),
        ),
        migrations.AddField(
            model_name='donation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Location'),
        ),
    ]
