# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-11-21 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20181121_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='key',
            field=models.IntegerField(default=-1),
        ),
    ]
