# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-11-21 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_location_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='State',
            new_name='state',
        ),
    ]
