# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-11-22 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20181122_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='street',
        ),
        migrations.AddField(
            model_name='location',
            name='street_address',
            field=models.CharField(default='(street address)', max_length=128),
        ),
    ]
