# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-11-22 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20181122_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('User', 'Regular User'), ('Location Employee', 'Location Employee'), ('Manager', 'Manager'), ('Admin', 'Admin')], default='User', max_length=20),
        ),
    ]
