# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-11-22 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20181122_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(default='unsaved', unique=True),
        ),
    ]
