# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-11-22 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_location_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
