# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-11-22 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_auto_20181122_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Location'),
        ),
    ]
